openapi: 3.0.0
info:
  title: FGV - FaceTendance
  contact:
    name: Aim-Force Software SDN BHD
    url: http://www.aim-force.com.my
  version: 0.1.0-alpha
  license:
    name: Proprietary
    url: https://jasxir.github.io/fgv/face-tendance/openapi

  description: API for retrieving and managing all data related to attendance including supervisor, worker, attendance records.
servers:
  - url: "https://{host}/api/{version}"
    description: Example FaceTendance Server
    variables:
      host:
        default: "facetendance.fgvholdings.com"
        description: Staging Server
      version:
        default: "v1"

paths:
  /estates/{estateId}/supervisors:
    get:
      summary: Get Supervisor List
      description: Downloads a list of all supervisors associated with a specific estate ID.
      security: []
      operationId: getSupervisorsByEstate
      tags:
        - Supervisors
      parameters:
        - name: estateId
          in: path
          required: true
          description: The unique ID of the estate.
          schema:
            type: string
            example: "01403226" # Use a sample ID here
      responses:
        "200":
          description: A successful response containing an array of supervisors.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Supervisor"
              example:
                - id: "01403226"
                  name: "MOHD ASRI BIN MOHD RAZALI"
                - id: "01403462"
                  name: "NORHAZAWATI BT HASSAN"
                - id: "01404540"
                  name: "MOHD KHAIDAN BIN NAZERI"
        "404":
          description: The estate ID was not found.
        "500":
          description: Internal server error.

  /estates/{estateId}/workers:
    get:
      summary: Get Worker List
      description: Downloads a list of all workers associated with a specific estate ID.
      security: []
      operationId: getWorkersByEstate
      tags:
        - Workers
      parameters:
        - name: estateId
          in: path
          required: true
          description: The unique ID of the estate.
          schema:
            type: string
            example: "01403226"
      responses:
        "200":
          description: A successful response containing an array of workers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Worker"
              example:
                - id: LW03200020
                  name: AZLIZAN BIN AB RAHMAN
                  type: LOCAL
                  supervisorId: "01403462"
                - id: FW03200993
                  name: HOSSEN MD SANWAR
                  type: FOREIGN
                  supervisorId: "01403462"
                - id: FC32025000
                  name: ROZIKIN
                  type: FOREIGN
                  supervisorId: "01403226"
        "404":
          description: The estate ID was not found.
        "500":
          description: Internal server error.

  /workers/{workerId}/attendance:
    get:
      operationId: getWorkerAttendance
      security: []
      summary: Get Worker Attendance History
      description: Returns a list of attendance records for the worker. By default, it returns the last 20 days.
      tags:
        - Attendance
      parameters:
        - name: workerId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Number of records to return.
          schema:
            type: integer
            default: 20
      responses:
        "200":
          description: A list of attendance records.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AttendanceRecord"
              example:
                - workerId: "FC32025000"
                  supervisorId: "01403226"
                  attendanceCode: "0001"
                  workStart: "2026-04-16T08:00:00+08:00"
                  workEnd: "2026-04-16T17:00:00+08:00"
                  rest1Start: "2026-04-16T10:00:00+08:00"
                  rest1End: "2026-04-16T10:15:00+08:00"
                  rest2Start: "2026-04-16T13:00:00+08:00"
                  rest2End: "2026-04-16T14:00:00+08:00"
                  overtimeStart: "2026-04-16T17:30:00+08:00"
                  overtimeEnd: "2026-04-16T19:30:00+08:00"
                - workerId: "FC32025000"
                  supervisorId: "01403226"
                  attendanceCode: "0001"
                  workStart: "2026-04-16T08:00:00+08:00"
                  workEnd: "2026-04-16T17:00:00+08:00"
                  rest1Start: "2026-04-16T10:00:00+08:00"
                  rest1End: "2026-04-16T10:15:00+08:00"
                  rest2Start: "2026-04-16T13:00:00+08:00"
                  rest2End: "2026-04-16T14:00:00+08:00"
                  overtimeStart: "2026-04-16T17:30:00+08:00"
                  overtimeEnd: "2026-04-16T19:30:00+08:00"
        "404":
          description: Worker not found.

    post:
      operationId: uploadWorkerAttendance
      security: []
      summary: Save Attendance Record
      description: Records a new attendance entry (Clock-in/Clock-out) for the worker.
      tags:
        - Attendance
      parameters:
        - name: workerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttendanceRecord"
      responses:
        "201":
          description: Attendance recorded successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateResponse"
        "400":
          description: Invalid data provided.

  /workers/{workerId}/photo:
    get:
      operationId: getWorkerPhoto
      security: []
      summary: Download Worker Photo
      tags:
        - Workers
      parameters:
        - name: workerId
          in: path
          required: true
          schema:
            type: string
        - name: since
          in: query
          required: false
          description: ISO 8601 timestamp. If provided, the server returns 304 if the photo hasn't changed since this time.
          schema:
            type: string
            format: date-time
            example: "2026-04-16T15:30:00+08:00"
      responses:
        "200":
          description: The worker's photo in JPEG format.
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        "304":
          description: Not Modified. The photo hasn't changed since the 'since' timestamp.
        "404":
          description: Worker or photo not found.
    put:
      operationId: uploadWorkerPhoto
      security: []
      summary: Upload Worker Photo
      description: Uploads or updates the worker's photo. Returns the timestamp of the update.
      tags:
        - Workers
      parameters:
        - name: workerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          image/jpeg:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Photo uploaded successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateResponse"

        "400":
          description: Invalid image format.

  /workers/{workerId}/embeddings/fp32:
    get:
      operationId: getWorkerEmbeddingFP32
      security: []
      summary: Download Worker Face Embedding (FP32)
      description: Returns the facial embedding vector in 32-bit floating point format.
      tags:
        - Workers
      parameters:
        - name: workerId
          in: path
          required: true
          schema:
            type: string
        - name: since
          in: query
          required: false
          description: ISO 8601 timestamp.
          schema:
            type: string
            format: date-time
            example: "2026-04-16T15:30:00+08:00"
      responses:
        "200":
          description: Successfully retrieved FP32 embedding.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
                  format: float
        "304":
          description: Not Modified.
        "404":
          description: Worker or embedding not found.
    put:
      security: []
      operationId: uploadWorkerEmbeddingFP32
      summary: Upload Worker Face Embedding (FP32)
      tags:
        - Workers
      parameters:
        - name: workerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
                format: float
      responses:
        "200":
          description: FP32 Embedding uploaded successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateResponse"
        "400":
          description: Bad Request. The embedding array is malformed or has incorrect dimensions.

  /workers/{workerId}/embeddings/hv-int8:
    get:
      operationId: getWorkerEmbeddingHVInt8
      security: []
      summary: Download Worker Face Embedding (Hikvision-INT8)
      description: Returns the facial embedding vector in high efficiency Hikvision proprietary INT8 format.
      tags:
        - Workers
      parameters:
        - name: workerId
          in: path
          required: true
          schema:
            type: string
        - name: since
          in: query
          required: false
          description: ISO 8601 timestamp.
          schema:
            type: string
            format: date-time
            example: "2026-04-16T15:30:00+08:00"
      responses:
        "200":
          description: Successfully retrieved Hikvision-INT8 embedding.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int32 # Representing the 8-bit values in a standard integer array
        "304":
          description: Not Modified.
        "404":
          description: Worker or embedding not found.
    put:
      security: []
      operationId: uploadWorkerEmbeddingHVInt8
      summary: Upload Worker Face Embedding (Hikvision-INT8)
      tags:
        - Workers
      parameters:
        - name: workerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                format: int32
      responses:
        "200":
          description: Hikvision-INT8 Embedding uploaded successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateResponse"
        "400":
          description: Bad Request. The embedding array is malformed or has incorrect dimensions.

components:
  schemas:
    Supervisor:
      $ref: schemas/Supervisor.yaml#/Supervisor
    Worker:
      $ref: schemas/Worker.yaml#/Worker
    UpdateResponse:
      $ref: schemas/UpdateResponse.yaml#/UpdateResponse
    AttendanceRecord:
      $ref: schemas/AttendanceRecord.yaml#/AttendanceRecord
